Repository KeunSori/KeunSori-Server, pull requests merged in 2025-01, with the labels that each got.

#5 feat: local 환경 MySQL 연동 설정 추가
  .gitignore
  build.gradle
  src/main/resources/application-datasource.yml
  src/main/resources/application-local.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 🌎environment

#6 feat:member entity 생성
  src/main/java/com/keunsori/keunsoriserver/member/Member.java
  src/main/java/com/keunsori/keunsoriserver/member/MemberStatus.java
Labels: ✨feature

#12 feat: Base Entity 작성, Member 엔티티 approvalDate 추가
  src/main/java/com/keunsori/keunsoriserver/KeunSoriServerApplication.java
  src/main/java/com/keunsori/keunsoriserver/domain/common/BaseEntity.java
  src/main/java/com/keunsori/keunsoriserver/domain/member/domain/Member.java
  src/main/java/com/keunsori/keunsoriserver/domain/member/domain/vo/MemberStatus.java
  src/main/java/com/keunsori/keunsoriserver/domain/member/repository/MemberRepository.java
  src/main/java/com/keunsori/keunsoriserver/member/Member.java
  src/main/java/com/keunsori/keunsoriserver/member/MemberStatus.java
Labels: ✨feature

#2 feat: 연습실 예약 API 개발
  build.gradle
  src/main/java/com/keunsori/keunsoriserver/domain/member/domain/Member.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/controller/ReservationController.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/Reservation.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/vo/ReservationType.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/vo/Session.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/dto/requset/ReservationCreateRequest.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/dto/requset/ReservationUpdateRequest.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/service/ReservationService.java
  src/main/java/com/keunsori/keunsoriserver/global/config/SecurityConfig.java
  src/main/java/com/keunsori/keunsoriserver/global/config/SwaggerConfig.java
  src/main/java/com/keunsori/keunsoriserver/global/exception/ErrorMessage.java
  src/main/java/com/keunsori/keunsoriserver/global/exception/ErrorResponse.java
  src/main/java/com/keunsori/keunsoriserver/global/exception/GlobalExceptionHandler.java
  src/main/java/com/keunsori/keunsoriserver/global/exception/ReservationException.java
  src/main/java/com/keunsori/keunsoriserver/global/security/JwtAuthenticationFilter.java
  src/main/java/com/keunsori/keunsoriserver/global/util/DateUtil.java
  src/main/java/com/keunsori/keunsoriserver/global/util/MemberUtil.java
Labels: ✨feature

#23 feat: 리스트 조회, 가입승인, 탈퇴API 추가
  src/main/java/com/keunsori/keunsoriserver/domain/admin/controller/AdminMemberController.java
  src/main/java/com/keunsori/keunsoriserver/domain/member/domain/Member.java
  src/main/java/com/keunsori/keunsoriserver/domain/member/dto/response/MemberApplicantResponse.java
  src/main/java/com/keunsori/keunsoriserver/domain/member/dto/response/MemberResponse.java
  src/main/java/com/keunsori/keunsoriserver/domain/member/repository/MemberRepository.java
  src/main/java/com/keunsori/keunsoriserver/domain/member/service/MemberService.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/Reservation.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/dto/requset/ReservationCreateRequest.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/keunsori/keunsoriserver/global/config/SecurityConfig.java
  src/main/java/com/keunsori/keunsoriserver/global/exception/ErrorMessage.java
  src/main/java/com/keunsori/keunsoriserver/global/exception/MemberException.java
Labels: ✨feature

#25 chore: 배포를 위한 도커 파일 작성
  Dockerfile
  build.gradle
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/dto/requset/ReservationCreateRequest.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/dto/requset/ReservationUpdateRequest.java
  src/main/java/com/keunsori/keunsoriserver/global/config/RedisConfig.java
  src/main/java/com/keunsori/keunsoriserver/global/properties/RedisProperties.java
  src/main/java/com/keunsori/keunsoriserver/global/security/JwtAuthenticationFilter.java
  src/main/resources/application-dev.yml
  src/main/resources/application-redis.yml
  src/main/resources/application.yml
  src/test/java/com/keunsori/keunsoriserver/KeunSoriServerApplicationTests.java
  src/test/resources/application-test.yml
Labels: 🌎environment

#29 fix: 예약 중복 생성 방지 및 예약 테스트 작성
  .github/workflows/dev-deploy.yml
  .github/workflows/dev-pr-test.yml
  build.gradle
  docker-compose-test.yml
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/controller/ReservationController.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/Reservation.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/validator/ReservationValidator.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/vo/ReservationType.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/vo/Session.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/dto/requset/ReservationCreateRequest.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/dto/requset/ReservationUpdateRequest.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/service/ReservationService.java
  src/main/java/com/keunsori/keunsoriserver/global/annotation/ValidEnum.java
  src/main/java/com/keunsori/keunsoriserver/global/config/MapperConfig.java
  src/main/java/com/keunsori/keunsoriserver/global/exception/ErrorMessage.java
  src/main/java/com/keunsori/keunsoriserver/global/exception/GlobalExceptionHandler.java
  src/main/java/com/keunsori/keunsoriserver/global/util/EnumValidator.java
  src/test/java/com/keunsori/keunsoriserver/common/ApiTest.java
  src/test/java/com/keunsori/keunsoriserver/common/DataCleaner.java
  src/test/java/com/keunsori/keunsoriserver/reservation/api/ReservationApiTest.java
  src/test/resources/application-test.yml
  src/test/resources/import.sql
Labels: 🐞bug
