Repository KeunSori/KeunSori-Server, pull requests merged in 2025-02, with the labels that each got.

#32 refactor: 다른 세션의 경우 같은 시간대 예약이 가능하도록 수정
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/validator/ReservationValidator.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/dto/requset/ReservationCreateRequest.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/service/ReservationService.java
  src/main/java/com/keunsori/keunsoriserver/global/exception/ErrorMessage.java
  src/test/java/com/keunsori/keunsoriserver/common/ApiTest.java
  src/test/java/com/keunsori/keunsoriserver/reservation/api/ReservationApiTest.java
  src/test/resources/import.sql
Labels: ♻refactor

#39 chore: 운영 서버 설정 추가
  .github/workflows/prod-deploy.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🌎environment

#36 fix: 개발 환경 스웨거 CORS 에러 해결
  src/main/java/com/keunsori/keunsoriserver/global/config/SwaggerConfig.java
  src/main/java/com/keunsori/keunsoriserver/global/properties/SwaggerProperties.java
  src/main/java/com/keunsori/keunsoriserver/global/util/EnvironmentUtil.java
  src/test/resources/import.sql
Labels: 🐞bug

#34 chore: 예약 정렬 코드 추가
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/service/ReservationService.java
Labels: chore

#41 feat: 예약관리 API 작성
  src/main/java/com/keunsori/keunsoriserver/domain/admin/member/controller/AdminMemberController.java
  src/main/java/com/keunsori/keunsoriserver/domain/admin/member/dto/response/MemberApplicantResponse.java
  src/main/java/com/keunsori/keunsoriserver/domain/admin/member/service/AdminMemberService.java
  src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/controller/AdminReservationController.java
  src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/domain/DailySchedule.java
  src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/domain/WeeklySchedule.java
  src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/request/DailyScheduleUpdateOrCreateRequest.java
  src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/request/WeeklyScheduleUpdateRequest.java
  src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/response/DailyAvailableResponse.java
  src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/response/WeeklyScheduleResponse.java
  src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/repository/DailyScheduleRepository.java
  src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/repository/WeeklyScheduleRepository.java
  src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/service/AdminReservationService.java
  src/main/java/com/keunsori/keunsoriserver/domain/member/service/MemberService.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/controller/ReservationController.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/validator/ReservationValidator.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/service/ReservationService.java
  src/main/java/com/keunsori/keunsoriserver/global/exception/ErrorMessage.java
  src/main/java/com/keunsori/keunsoriserver/global/util/DayOfWeekUtil.java
Labels: ✨feature

#46 fix: 주간 스케줄 저장 시 500에러 해결
  src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/request/WeeklyScheduleUpdateRequest.java
  src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/response/DailyAvailableResponse.java
  src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/response/WeeklyScheduleResponse.java
Labels: 🐞bug

#57 feat: 예약관리 관련 기능 추가
  src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/response/DailyAvailableResponse.java
  src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/response/WeeklyScheduleResponse.java
  src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/service/AdminReservationService.java
  src/main/java/com/keunsori/keunsoriserver/domain/member/domain/Member.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/Reservation.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/repository/ReservationRepository.java
Labels: ✨feature

#59 feat: 예약 타입에 교습 타입 추가
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/validator/ReservationValidator.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/vo/ReservationType.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/vo/Session.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/service/ReservationService.java
  src/main/java/com/keunsori/keunsoriserver/global/exception/ErrorMessage.java
  src/test/java/com/keunsori/keunsoriserver/reservation/api/ReservationApiTest.java
  src/test/java/com/keunsori/keunsoriserver/reservation/domain/ReservationTypeTest.java
Labels: ✨feature

#69 chore: 운영서버 host 설정
  .github/workflows/prod-deploy.yml
Labels: 🌎environment

#61 chore: cors origin 세팅
  src/main/java/com/keunsori/keunsoriserver/global/config/SecurityConfig.java
  src/main/java/com/keunsori/keunsoriserver/global/config/WebConfig.java
  src/main/java/com/keunsori/keunsoriserver/global/constant/EnvironmentConstant.java
Labels: 🌎environment, chore

#71 chore: 에러 및 정규 표현식 상수화
  src/main/java/com/keunsori/keunsoriserver/domain/auth/controller/AuthController.java
  src/main/java/com/keunsori/keunsoriserver/domain/auth/login/LoginService.java
  src/main/java/com/keunsori/keunsoriserver/domain/auth/login/dto/request/LoginRequest.java
  src/main/java/com/keunsori/keunsoriserver/domain/auth/redis/RefreshTokenService.java
  src/main/java/com/keunsori/keunsoriserver/domain/member/sign_up/dto/request/SignUpRequest.java
  src/main/java/com/keunsori/keunsoriserver/global/constant/RequestFormatConstant.java
  src/main/java/com/keunsori/keunsoriserver/global/exception/ErrorMessage.java
  src/main/java/com/keunsori/keunsoriserver/global/exception/GlobalExceptionHandler.java
Labels: chore

#75 feat: 이메일 인증 기능 추가
  build.gradle
  src/main/java/com/keunsori/keunsoriserver/domain/email/controller/EmailController.java
  src/main/java/com/keunsori/keunsoriserver/domain/email/domain/EmailAuthentication.java
  src/main/java/com/keunsori/keunsoriserver/domain/email/dto/request/AuthNumberSendRequest.java
  src/main/java/com/keunsori/keunsoriserver/domain/email/dto/request/AuthNumberVerifyRequest.java
  src/main/java/com/keunsori/keunsoriserver/domain/email/repository/EmailRepository.java
  src/main/java/com/keunsori/keunsoriserver/domain/email/service/EmailService.java
  src/main/java/com/keunsori/keunsoriserver/global/config/EmailConfig.java
  src/main/java/com/keunsori/keunsoriserver/global/config/RedisConfig.java
  src/main/java/com/keunsori/keunsoriserver/global/config/SecurityConfig.java
  src/main/java/com/keunsori/keunsoriserver/global/exception/EmailException.java
  src/main/java/com/keunsori/keunsoriserver/global/exception/ErrorMessage.java
  src/main/java/com/keunsori/keunsoriserver/global/exception/GlobalExceptionHandler.java
  src/main/java/com/keunsori/keunsoriserver/global/util/EmailUtil.java
  src/main/resources/application-email.yml
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: ✨feature

#82 fix: 예약 리스트 2달치 보내주도록 변경
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/service/ReservationService.java
Labels: 🐞bug

#83 fix: 예약 리스트 2달치 보내주도록 변경
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/service/ReservationService.java
Labels: 🐞bug

#84 refactor: 학번 유니크 제약 추가 및 회원가입 패키지 리팩토링
  src/main/java/com/keunsori/keunsoriserver/domain/member/controller/SignUpController.java
  src/main/java/com/keunsori/keunsoriserver/domain/member/domain/Member.java
  src/main/java/com/keunsori/keunsoriserver/domain/member/dto/request/SignUpRequest.java
  src/main/java/com/keunsori/keunsoriserver/domain/member/dto/response/SignUpResponse.java
  src/main/java/com/keunsori/keunsoriserver/domain/member/repository/MemberRepository.java
  src/main/java/com/keunsori/keunsoriserver/domain/member/service/SignUpService.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/dto/requset/ReservationCreateRequest.java
  src/main/java/com/keunsori/keunsoriserver/domain/reservation/dto/requset/ReservationUpdateRequest.java
  src/main/java/com/keunsori/keunsoriserver/global/config/SecurityConfig.java
  src/main/java/com/keunsori/keunsoriserver/global/config/SwaggerConfig.java
  src/main/java/com/keunsori/keunsoriserver/global/util/EnumValidator.java
  src/test/java/com/keunsori/keunsoriserver/common/ApiTest.java
  src/test/java/com/keunsori/keunsoriserver/common/DataCleaner.java
  src/test/java/com/keunsori/keunsoriserver/member/api/MemberApiTest.java
  src/test/java/com/keunsori/keunsoriserver/reservation/api/ReservationApiTest.java
  src/test/resources/import.sql
Labels: ♻refactor
